version = 1

[[analyzers]]
name = "cfn-lint"
type = "community"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "javascript"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "standardrb"

[[transformers]]
name = "standardjs"